name: Publish

on:
  release:
    types: [published]

jobs:
  publish-vsce:
    name: Publish VSCE
    runs-on: ubuntu-latest
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
    steps:
      - name: Download Artifact from GitHub Release
        run: gh release download ${{ github.event.release.tag_name }} --pattern "openscad-preview.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Microsoft Marketplace
        if: env.VSCE_PAT != ''
        run: npx @vscode/vsce publish -p ${{ env.VSCE_PAT }} --packagePath openscad-preview.vsix

      - name: Skip Notification
        if: env.VSCE_PAT == ''
        run: echo "Skipped publication because VSCE_PAT is missing."

  publish-ovsx:
    name: Publish OVSX
    runs-on: ubuntu-latest
    env:
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
    steps:
      - name: Download Artifact from GitHub Release
        run: gh release download ${{ github.event.release.tag_name }} --pattern "openscad-preview.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Open VSX
        if: env.OVSX_PAT != ''
        run: npx ovsx publish -p ${{ env.OVSX_PAT }} --packagePath openscad-preview.vsix

      - name: Skip Notification
        if: env.OVSX_PAT == ''
        run: echo "Skipped publication because OVSX_PAT is missing."
